### ISSUE TITLE
Sylvain: problem with 'horizon' in 'forecast_cases'

### ISSUE THREAD

**Issue by tuxette** [tuxette/EpiSoon#13]
'horizon' appears to have no effect <https://github.com/epiforecasts/EpiSoon/issues/42>

**Comment by tuxette** [comment]
For me, this is not a bug but simply a lack of warning or message. When the supplied horizon is larger than the horizon used for the forecast, the forecast horizon is used, which is what I would have done (probably giving a message to the user but for me, this is not a bug).

**Comment by maressyl** [comment]
Actually I have the feeling this `horizon` argument has no effect at all, as the 3 examples I wrote all give the exact same result. But I'm not sure if it is expected or not, I don't understand this function deeply enough so far.

**Comment by tuxette** [comment]
I'll check (it is a bit strange that the outputs are exactly the same but not totally impossible).

**Comment by tuxette** [comment]
Bug fixed on branch 'bughorizon' (it was due to non standard evaluation of tidyverse and confusion in naming argument/column). Unit tests updated accordingly that check the proper behavior (as described by the authors in their answer of #42). Pull request sent to authors today.
